### DISCUSSION TITLE
How to configure ArtifactHUB with Keycloak?

### DISCUSSION THREAD

**Discussion by stranljip** [artifacthub/hub#2336] [Show and tell]
I wanted to connect our own instance of ArtifactHUB to our Keycloak IDP. Since the documentation on that is a little bit thin I had to figure it out on my my with help from @tegioz (Kudos to you!). The necessary steps are:
- set up a new client in your realm in Keycloak (confidential)
- enable oidc in your Helm values:
```
(...)
    oauth:
      oidc:
        # Enable OIDC
        enabled: true
        # OpenID connect issuer url
        issuerURL: "https://keycloak.example.org/auth/realms/<myrealm>"
        # OpenID connect oauth client id
        clientID: "<my_client_id>"
        # OpenID connect oauth client secret
        clientSecret: "<my_client_secret>"
        # OpenID connect oauth redirect url
        redirectURL: "https://<my_artifacthub_url>/oauth/oidc/callback"
        # OpenID connect oauth scopes
        scopes:
          - openid
          - profile
          - email
        # Skip email verified check
        skipEmailVerifiedCheck: false
(...)
```
After that - redeploy and you can login to your ArtifactHUB installation :-)
