### ISSUE TITLE
Structured Changelog Annotation

### ISSUE THREAD

**Issue by oliverbaehler** [artifacthub/hub#1039]
Hi there

I was playing around with the `artifacthub.io/changes` annotation. I tried to have a nice structure for each type of change (as we know changelogs). So I ended up with something like this: 

``` 
annotations:
  artifacthub.io/changes: |
    - [Added] Allow Vanilla Tavern Tests
    - [Added] Return empty when no tests are defined
    - [Added] Dumy Test as default (Allows linting)
    - [Changed] Define `manifests` dependency more loose
    - [Fixed] Moved to new `library` naming
``` 

But I noticed this won't be rendered. I assume it's because of the `[]` but I am not quiet sure. I was wondering if it would be possible to have a little bit more sophisticated changelog annotation. For example it could look like the images annotation:

``` 
annotations:
  artifacthub.io/changes: |
    - change: "Fixed minor bug" 
      type: "Added"
    - change: "Return empty when no tests are defined" 
      type: "Added"
    - change: "Dumy Test as default (Allows linting)" 
      type: "Added"
    - change: "Define `manifests` dependency more loose" 
      type: "Changed"
    - change: "Moved to new `library` naming" 
      type: "Fixed"
``` 

I feel like this could be very useful to have a more structured changelog rendered. Let me know what you think about it :).

**Comment by tegioz** [comment]
Hi @oliverbaehler 👋 

Some special characters (like `[` or `]`) may require you to put your string values between quotes.

```yaml
annotations:
  artifacthub.io/changes: |
    - "[TEST] Testing line with brackets"
```

<img width="1181" alt="Screen Shot 2021-01-25 at 11 10 25" src="https://user-images.githubusercontent.com/1213902/105692079-48bd4600-5efe-11eb-8e85-33033484df1b.png">

Regarding having a more sophisticated changelog annotation, we can see what other people think about this. I'd rather not changing or overloading the one we have as it's used already by many packages, but we can always add another annotation if we find a better format that provides more value (and that users can agree on 😉).

Please keep in mind that the list of changes each version provides is also used in email notifications, as well as in the payload passed to webhooks, so we need to be careful making changes to it.

<img width="1127" alt="Screen Shot 2021-01-25 at 11 24 37" src="https://user-images.githubusercontent.com/1213902/105693399-f7ae5180-5eff-11eb-804b-8181fd1829b5.png">
