### ISSUE TITLE
Pre-release version is listed as the default version

### ISSUE THREAD

**Issue by wallrj** [artifacthub/hub#1359]
In https://github.com/artifacthub/hub/issues/973 @datamattsson wrote 
> The "-beta" tag appears as default in ArtifactHub UI

And that issue was closed when the `artifacthub.io/prerelease` annotation was introduced along with the ignore feature in the metadata.
But we have found that neither of these work.

We have the following stanza in `artifacthub-repo.yml` :

```yaml
ignore:
  - name: cert-manager
    version: '^v\d+\.\d+\.\d+-alpha\.\d+$'
  - name: cert-manager
    version: '^v\d+\.\d+\.\d+-beta\.\d+$'
```

And we have now added the prerelease annotation to our chart:

```sh
$ helm show chart  jetstack/cert-manager --devel

annotations:
  artifacthub.io/prerelease: "true"
apiVersion: v1
appVersion: v1.4.0-beta.0
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
keywords:
- cert-manager
- kube-lego
- letsencrypt
- tls
maintainers:
- email: cert-manager-maintainers@googlegroups.com
  name: cert-manager-maintainers
name: cert-manager
sources:
- https://github.com/jetstack/cert-manager
version: v1.4.0-beta.0

```

And yet, the cert-manager v1.4.0-beta.0 release still shows up as the default:
![image](https://user-images.githubusercontent.com/978965/120019156-0147e300-bfe0-11eb-9119-06d746fbc53a.png)

albeit with a prerelease badge added.

And the default installation instructions at https://artifacthub.io/packages/helm/cert-manager/cert-manager still instruct users to install the beta.

Upon releasing cert-manager v1.4.0-beta.0, I expected the https://artifacthub.io/packages/helm/cert-manager/cert-manager page to continue to show the last alpha release, which did not have the prerelease annotation.

And the change that we made to `artifacthub-repo.yml` does not seem to have had any effect, unless our regexp is wrong :thinking: .

Please take a look.

**Comment by tegioz** [comment]
Hi @wallrj 👋 

The pre-release behavior is working as expected. When this flag is used, we warn users both in the package view and the installation modal about the pre-release status. This way they can decide if they want to go for it or pick a stable one. That seems to be ok in the `cert-manager` package at the moment.

Regarding the regular expression, I've just taken a quick look at it and it looks like the problem is the `v` at the beginning of it. If you take a look at your screenshot, you'll see that for Artifact Hub, the version is actually `1.4.0-beta.0`, without the `v` prefix. When a version is not strictly a valid semver value, we convert it when possible.

Hope this helps! Otherwise please let me know and I'll look into it.

**Comment by tegioz** [comment]
> Thanks for the pointer on the regular expression, we'll try that.

Cool, no worries 👍

> I would like the "install" button on https://artifacthub.io/packages/helm/cert-manager/cert-manager page to show the installation instructions for the last stable release version.
> 
> I would like the pre-release versions to be only visible when I click the "see all" link in the versions section.

One of the problems with the `pre-release` part of the semver version is that not all packages use it with the same expectations in mind. Please see my comment on the ticket you linked (https://github.com/artifacthub/hub/issues/973#issuecomment-745220868) for some examples. Also, we support plenty of packages' kinds, probably with more coming, and how each of the tools behind them handle pre-release versions may vary.

But I understand this is a real concern and we need to provide some mechanisms so that publishers can express their intentions clearly in Artifact Hub. Both the `ignore` and `pre-release` features were an attempt to improve this situation, so we'll keep thinking about more options so make it better 🙂 The channels idea mentioned in that comment as well could be another one, for example.

I'll close this issue for now as everything seems to be working as expected. Please ping me if you run into any problem with the `ignore` field.

**Comment by wallrj** [comment]
@tegioz We updated the regexp, removing the `v` prefix as you suggested, but still the alpha and beta versions are showing at https://artifacthub.io/packages/helm/cert-manager/cert-manager

```sh
$ curl https://charts.jetstack.io/artifacthub-repo.yml
```

```yaml
# This file is served at https://charts.jetstack.io/artifacthub-repo.yml. The purpose
# of this file is detailed at https://artifacthub.io/docs/topics/repositories/\#ownership-claim.
#
# We configure ArtifactHUB to ignore alpha and beta releases because otherwise
# pre-releases are presented to users as the default version.
# See https://github.com/artifacthub/hub/issues/1359
#
# The regular expressions used in the ignore stanzas below omit the `v` prefix,
# because ArtifactHUB strips this from the Helm package version before matching
# and filtering.
# See https://github.com/artifacthub/hub/issues/1359#issuecomment-850577581
# > When a version is not strictly a valid semver value, we [ArtifactHUB]
# > convert it when possible.
repositoryID: f4c99bff-136d-4481-b701-9964b6c28e6e # For  "verified publisher"
owners: # (optional, used to claim repository ownership)
  - name: jetstack
    email: tech+artifacthub@jetstack.io
ignore:
  - name: cert-manager
    version: '^\d+\.\d+\.\d+-alpha\.\d+$'
  - name: cert-manager
    version: '^\d+\.\d+\.\d+-beta\.\d+$'

```
