### ISSUE TITLE
error getting repository remote digest: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile

### ISSUE THREAD

**Issue by Vad1mo** [artifacthub/hub#1795]
**Describe the bug**
We host helm charts in artifacthub.io to the public and since a week we see that artifacthub.io has issue scraping our chartrepo.

the error message we see is:

Tracking errors log - 8gears open source
Wed, Jan 19, 2022 10:00 PM +01:00
```
error getting repository remote digest: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile
```

Repo id is `b37cafa3-373b-42f7-8020-7a577030f0cd`

This is the url to our repo: 

```sh
https://8gears.container-registry.com/chartrepo/library/index.yaml
```
and it contains the followind yaml:

```yaml
apiVersion: v1
entries:
  clickhouse:
  - apiVersion: v2
    appVersion: "20.8"
    created: "2020-11-20T16:09:13Z"
    description: ClickHouse is an open source column-oriented database management
      system capable of real time generation of analytical data reports using SQL
      queries
    digest: c4573a3a0957597dcd3c2ba7757a5af474293bc03c1555741b92d18ac125f6da
    home: https://clickhouse.yandex/
    icon: https://clickhouse.yandex/images/logo.png
    keywords:
    - clickhouse
    - olap
    - database
    maintainers:
    - email: https://github.com/Vad1mo
      name: Vad1mo
    - email: https://github.com/8gears
      name: 8gears
    name: clickhouse
    sources:
    - https://github.com/8gears/clickhouse-helm-chart
    - https://8gears.com
    urls:
    - charts/clickhouse-1.0.2.tgz
    version: 1.0.2
  n8n:
  - apiVersion: v2
    appVersion: 0.111.0
    created: "2021-03-19T07:14:55Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: ff1346c193fbf191da01b94b6180d0a9a78822ed391484d9ff8f27bb3c907463
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.110.3
    created: "2021-03-19T07:14:44Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: 26af10477f9a6c4548036c69afe32a5f6386322a193b8ea935d7e451c000c96d
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.109.0
    created: "2021-02-24T12:40:03Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: 8946dff6aac514f9c6ea70ac6fcf0a69f742dc44f917699eed8c3089f17bfe5e
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.100.0
    created: "2021-01-05T21:57:16Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: c4adbad95abe840ede78cd1ee873be1521689407c9be9e1ca7f6efd6ee1ad6f7
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.94.1
    created: "2020-11-26T21:14:43Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: ddc1f6d7e1b9acda712ab5544a1818a41fecc81ad6cf16ac5df09c6d12f955d8
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.94.1
    created: "2020-11-26T16:08:11Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: cad576d4dff05b2720e20a4dcd1481af8a434ac2611754da3640ae8752396c5f
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.94.1
    created: "2020-11-26T14:06:40Z"
    description: A Kubernetes Helm chart for n8n a free and open fair-code licensed
      node based Workflow Automation Tool. Easily automate tasks across different
      services.
    digest: 94ce496ed709ac8248adb77c98955c675d3f054c109813b86d1d751638d31bc0
    home: https://github.com/8gears/n8n-helm-chart
    icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
    keywords:
    - Workflow Automation
    - Workflow
    - iPaaS
    - integration-framework
    - low-code-plattform
    - low-code
    maintainers:
    - name: Vadim Bauer
    name: n8n
    sources:
    - https://n8n.io/
    - https://github.com/n8n-io/n8n
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/n8n/versions/0.1.0
    type: application
    urls:
    - charts/n8n-0.1.0.tgz
    version: 0.1.0
  plausible-analytics:
  - apiVersion: v2
    appVersion: v1.1.1
    created: "2020-11-24T13:16:06Z"
    description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly
      alternative to Google Analytics
    digest: 20f724ceb66e04436a4be8dc288d13453f1d07c73a1a9ec1953e3173df40b62e
    home: https://plausible.io/
    icon: https://docs.plausible.io/img/logo.svg
    keywords:
    - plausible analytics
    - analytics
    maintainers:
    - name: Vadim Bauer
      url: https://8gears.com
    name: plausible-analytics
    sources:
    - https://github.com/8gears/plausible-analytics-helm-chart
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/plausible-analytics/versions/0.1.0
    - https://github.com/plausible/analytics
    type: application
    urls:
    - charts/plausible-analytics-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v1.1.1
    created: "2020-11-20T23:21:51Z"
    description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly
      alternative to Google Analytics
    digest: 02de3f8f5c23b2c390c16946c68163231fb74154d85ec46eccae365c31de6643
    home: https://plausible.io/
    icon: https://docs.plausible.io/img/logo.svg
    keywords:
    - plausible analytics
    - analytics
    maintainers:
    - name: Vadim Bauer
      url: https://8gears.com
    name: plausible-analytics
    sources:
    - https://github.com/8gears/plausible-analytics-helm-chart
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/plausible-analytics/versions/0.1.0
    - https://github.com/plausible/analytics
    type: application
    urls:
    - charts/plausible-analytics-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v1.1.1
    created: "2020-11-20T15:53:01Z"
    description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly
      alternative to Google Analytics
    digest: 39f3333cd819c9e16261b3e301d3face5111a186f60d898197c0951f06d6f544
    home: https://plausible.io/
    icon: https://docs.plausible.io/img/logo.svg
    keywords:
    - plausible analytics
    - analytics
    maintainers:
    - name: Vadim Bauer
      url: https://8gears.com
    name: plausible-analytics
    sources:
    - https://github.com/8gears/plausible-analytics-helm-chart
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/plausible-analytics/versions/0.1.0
    - https://github.com/plausible/analytics
    type: application
    urls:
    - charts/plausible-analytics-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v1.1.1
    created: "2020-11-18T19:24:43Z"
    description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly
      alternative to Google Analytics
    digest: f81cf38025a2996faf9391cdcc55b196b266532a57f9a43748b85d6c7a9b94c5
    home: https://plausible.io/
    icon: https://docs.plausible.io/img/logo.svg
    keywords:
    - plausible analytics
    - analytics
    maintainers:
    - name: Vadim Bauer
      url: https://8gears.com
    name: plausible-analytics
    sources:
    - https://github.com/8gears/plausible-analytics-helm-chart
    - https://8gears.container-registry.com/harbor/projects/1/helm-charts/plausible-analytics/versions/0.1.0
    - https://github.com/plausible/analytics
    type: application
    urls:
    - charts/plausible-analytics-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-19T07:15:29Z"
serverInfo: {}
```

**Additional context**
Unfortunatly it is not clear to me where exactly the problem is.
