### ISSUE TITLE
[ABUSE-REPORT] nacos 集群部署，使用外部数据库报错

### ISSUE THREAD

**Issue by evescn** [artifacthub/hub#1957]
**Describe the problem**
chart 版本：2.0.1
nacos 版本： 2.0.4
url地址：https://artifacthub.io/packages/helm/ygqygq2/nacos

values.yaml文件中，使用外部数据库，配置 mysql.enabled = false，会出现  templates/secret.yaml 模板文件渲染报错，详细报错信息如下

```
mysql:
  enabled: false
  # 启用外部存储，而不是自建 mysql 主从
  # 可以自建 nacos 用户，这里此处直接使用了 root 账户进行 mysql 集群登陆
  # 需要去数据库新建 nacos 数据库
  external:
    mysqlMasterHost: "mysql-cluster-mysql.test-middleware"
    mysqlDatabase: "nacos"
    mysqlMasterPort: "3306"
    mysqlMasterUser: "root"
    mysqlMasterPassword: "root123"
    mysqlSlaveHost: "mysql-cluster-mysql-slave.test-middleware"
    mysqlSlavePort: "3306"
```

**Additional context**
Error: INSTALLATION FAILED: YAML parse error on nacos/templates/secret.yaml: error converting YAML to JSON: yaml: line 12: could not find expected ':'

对 secret.yaml 模板进行调整后 正常，调整后模板如下：

```
$ cat /root/nacos/nacos/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nacos.fullname" . }}
  labels:
    app: {{ template "nacos.name" . }}
    chart: {{ template "nacos.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
data:  # 修改了 data中 if else 配置， 对 if else 配置进行了调整
{{- if .Values.mysql.enabled }}
  mysqlMasterHost: {{ (include "nacos.mysql.primaryHost" .) | b64enc | quote }}
  mysqlDatabase: {{ .Values.mysql.auth.database | b64enc | quote }}
  mysqlMasterPort: {{ "3306" | b64enc }}
  mysqlMasterUser: {{ .Values.mysql.auth.username | b64enc | quote }}
  mysqlMasterPassword: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysqlSlaveHost: {{ (include "nacos.mysql.secondaryHost" .) | b64enc | quote }}
  mysqlSlavePort: {{ "3306" | b64enc }}
{{- else }}
  mysqlMasterHost: {{ .Values.mysql.external.mysqlMasterHost | b64enc | quote }}
  mysqlDatabase: {{ .Values.mysql.external.mysqlDatabase | b64enc | quote }}
  mysqlMasterPort: {{ .Values.mysql.external.mysqlMasterPort | b64enc }}
  mysqlMasterUser: {{ .Values.mysql.external.mysqlMasterUser | b64enc | quote }}
  mysqlMasterPassword: {{ .Values.mysql.external.mysqlMasterPassword | b64enc | quote}}
  mysqlSlaveHost: {{ .Values.mysql.external.mysqlSlaveHost | b64enc | quote }}
  mysqlSlavePort: {{ .Values.mysql.external.mysqlSlavePort | b64enc }}
{{- end }}
{{- if .Values.secret.enabled }}
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
```
