### ISSUE TITLE
Maintainers section show URL in the same way as email

### ISSUE THREAD

**Issue by carrodher** [artifacthub/hub#2024]
**Describe the bug**
The maintainers' email was replaced in the `Chart.yaml` since it was not used for providing support. The proper place to reach out to the Helm charts maintainers and receive support is through GH issues. Because of that, `maintainers.email` was replaced by `maintainers.url`.

According to the [official Helm specification](https://helm.sh/docs/topics/charts/#the-chartyaml-file), the `maintainers` object can contain the following config:
```yaml
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
```

Once implemented the above mentioned at https://github.com/bitnami/charts/pull/10523 the maintainers section disappeared from the ArtifactHub UI, probably because only the email is being taken into account.

**To Reproduce**
1. Go to https://artifacthub.io/packages/helm/bitnami/etcd
2. Look for "maintainers"

**Expected behavior**
I expect to see the metadata (URL and/or mail) present in the Helm chart's `Chart.yaml`, in this case:
```yaml
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
```
https://github.com/bitnami/charts/blob/7d41614a6e43ff6118a4310a3e72cf230bce94a8/bitnami/etcd/Chart.yaml#L20
