### ISSUE TITLE
Cannot change helm chart repository

### ISSUE THREAD

**Issue by mloiseleur** [artifacthub/hub#2516]
**Describe the bug**
At traefik, we were using one helm repo per each charts : helm.traefik.io/traefik, helm.traefik.io/mesh, etc.
Since we have switched to [one helm repo](https://traefik.github.io/charts/) for all our Charts, this new repo is not browsed by ArtifactHub.
We have this error log in artifacthub interface:
![image](https://user-images.githubusercontent.com/97035654/201649751-eb266234-63af-4c2d-9230-482413109c83.png)

Which is false, one can see a `description` in [index.yaml of this helm repo](https://traefik.github.io/charts/index.yaml):
```yaml
  traefik:
  - annotations:
      artifacthub.io/changes: |
        - fix: use consistent appVersion with Traefik Proxy
    apiVersion: v2
    appVersion: v2.9.4
    created: "2022-11-10T13:13:00.37650886Z"
    description: A Traefik based Kubernetes ingress controller
  [...]
    urls:
    - https://traefik.github.io/charts/traefik/traefik-20.1.1.tgz
    version: 20.1.1
```

**To Reproduce**
1. Go to [Repositories](https://artifacthub.io/control-panel/repositories?page=1) of Traefik Organization
2. Click on 'Show Tracking Errors Log'
3. See error

**Expected behavior**
This new unified helm repository is scanned correctly
