### ISSUE TITLE
Posibility to add Security Context

### ISSUE THREAD

**Issue by roldyxoriginal** [artifacthub/hub#2615]
I need to add security context, but the chart don't have the possibility to add it.
For example, I need to put in the values.yaml some thing like it:
```
securityContextHub:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
securityContextTrivy:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
```
Finally in the templates/hub_deployment.yaml and trivy_deployment.yaml respectly.
```
securityContext:
          {{- toYaml .Values.securityContextHub | nindent 12 }}
```
```
securityContext:
          {{- toYaml .Values.securityContextTrivy | nindent 12 }}
```

Thank you!
