### ISSUE TITLE
OLM package installation page: Untie “INSTALL” flow from the OperatorHub.io website

### ISSUE THREAD

**Issue by tlwu2013** [artifacthub/hub#2654]
**Is your feature request related to a problem? Please describe.**

After clicking the “INSTALL” button, the current pop-up modal for presenting installation command depends on the endpoint of the OperatorHub.io website: 
```
kubectl create -f https://operatorhub.io/install/v4/grafana-operator.yaml
```
This introduces some problems when the OperatorHub.io website is unreachable or a new (release-candidate) version of the OLM package is merged to the git repository but failed to be released to OperatorHub.io by its release pipeline (see issue [#1828](https://github.com/artifacthub/hub/issues/1828) in the past).

**Describe the solution you'd like**

ArtitfactHub.io website should be able to generate those installation manifests (and/or their filePaths) to untie the installation flow from the OperatorHub.io website so that it’s not depending on OperatorHub.io’s existence or availability.

_Proposal:_
* **Server-side of ArtifactHub.io**: Generates the required installation YAML manifests from the git repository for installing Operators 
* **Front-end of ArtifactHub.io**: Generates the required filePaths associated to ArtifactHub.io website itself for installation commands rather than depending on the OperatorHub.io as:
```
kubectl create -f https://artifacthub.io/install/v4/grafana-operator.yaml
```

**Describe alternatives you've considered**

_Alternative proposal:_
* Front-end of ArtifactHub.io: Generates those copy & paste-ready YAML manifests directly for installation commands: 

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
 name: my-grafana-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
 name: operatorgroup
 namespace: my-grafana-operator
spec:
 targetNamespaces:
 - my-grafana-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: my-grafana-operator
 namespace: my-grafana-operator
spec:
 channel: v4
 name: grafana-operator
 source: operatorhubio-catalog
 sourceNamespace: olm
EOF
```

**Additional context**
1. **ArtifactHub.io installation modal:**
![artifacthub_installation_modal](https://user-images.githubusercontent.com/5903705/211600891-e6213d56-22a4-4e55-a599-c7dff6505cb9.png)

2. **Server-side of OperatorHub.io**: Generates the required installation YAML manifests from the git repository
https://github.com/k8s-operatorhub/operatorhub.io/blob/main/server/src/services/installService.ts

3. **Front-end of OperatorHub.io**: Generates the required filePaths for installation command
https://github.com/k8s-operatorhub/operatorhub.io/blob/main/frontend/src/components/modals/InstallModal.tsx#L63-L76
