### ISSUE TITLE
Icon does not show up for codefresh-gitops-runtime chart

### ISSUE THREAD

**Issue by ilia-medvedev-codefresh** [artifacthub/hub#3051]
**Describe the bug**
Icon does not show up for https://artifacthub.io/packages/helm/codefresh-gitops-runtime/gitops-runtime even though provided in Chart.yaml and made sure the url points to a valid PNG file

**To Reproduce**
1. Go to :https://artifacthub.io/packages/helm/codefresh-gitops-runtime/gitops-runtime
2. The icon provided in Chart.yaml is not displayed 

This is Chart.yaml
`apiVersion: v2
appVersion: 0.1.29
description: A Helm chart for Codefresh gitops runtime
name: gitops-runtime
version: 0.2.1-alpha.14
home: https://github.com/codefresh-io/gitops-runtime-helm
icon: https://codefresh.io/wp-content/uploads/2022/02/Codefresh_Logo_Vertical_LightBkgd.png
keywords:
  - codefresh
  - gitops
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added support for custom CA
dependencies:
- name: argo-cd
  repository: https://codefresh-io.github.io/argo-helm
  version: 5.29.1-1-cap-CR-17237
- name: argo-events
  repository: https://codefresh-io.github.io/argo-helm
  version: 2.0.5-1-cf-init
- name: argo-workflows
  repository: https://codefresh-io.github.io/argo-helm
  version: 0.22.9-1-CR-17426
  condition: argo-workflows.enabled
- name: argo-rollouts
  repository: https://codefresh-io.github.io/argo-helm
  version: 2.22.1-1-cap-sw
  condition: argo-rollouts.enabled
- name: sealed-secrets
  repository: https://bitnami-labs.github.io/sealed-secrets/
  version: 2.7.3
- name: codefresh-tunnel-client
  repository: https://chartmuseum.codefresh.io/codefresh-tunnel-client
  version: "0.1.12"
  alias: tunnel-client`

**Screenshots**
The file is a valid png 
<img width="698" alt="image" src="https://github.com/artifacthub/hub/assets/106013343/b7dc513e-6b82-4b73-b7da-fd4d71240ba6">
This is how it looks in artifacthub
![image](https://github.com/artifacthub/hub/assets/106013343/8840d4ad-df5b-4d13-8196-5dcd300a2504)

**Comment by tegioz** [comment]
Hi @ilia-medvedev-codefresh 👋 

Version `0.2.1-alpha.9` (latest at the moment) does not seem to contain the icon entry in the Chart.yaml file.

I've just checked both the [repo index.yaml file](https://chartmuseum.codefresh.io/gitops-runtime/index.yaml) and the [version tgz package](https://chartmuseum.codefresh.io/gitops-runtime/charts/gitops-runtime-0.2.1-alpha.9.tgz) and I can't find it in any of them.

Hope that helps 🙂

**Comment by tegioz** [comment]
For reference:

(Entry in index.yaml)

```yaml
  - apiVersion: v2
    appVersion: 0.1.27
    created: "2023-04-23T12:02:14Z"
    dependencies:
    - name: argo-cd
      repository: https://codefresh-io.github.io/argo-helm
      version: 5.29.1-1-cap-CR-17237
    - name: argo-events
      repository: https://codefresh-io.github.io/argo-helm
      version: 2.0.5-1-cf-init
    - condition: argo-workflows.enabled
      name: argo-workflows
      repository: https://codefresh-io.github.io/argo-helm
      version: 0.22.9-1-CR-17426
    - condition: argo-rollouts.enabled
      name: argo-rollouts
      repository: https://codefresh-io.github.io/argo-helm
      version: 2.22.1-1-cap-sw
    - name: sealed-secrets
      repository: https://bitnami-labs.github.io/sealed-secrets/
      version: 2.7.3
    - alias: tunnel-client
      name: codefresh-tunnel-client
      repository: https://chartmuseum.codefresh.io/codefresh-tunnel-client
      version: 0.1.12
    description: A Helm chart for Codefresh gitops runtime
    digest: 14c1d6d1bf9a1594740adf54ea37a6b97b62f3e3d3fb73d62acd531ce24f1077
    home: https://github.com/codefresh-io/gitops-runtime-helm
    keywords:
    - codefresh
    - gitops
    maintainers:
    - name: codefresh
      url: https://codefresh-io.github.io/
    name: gitops-runtime
    urls:
    - charts/gitops-runtime-0.2.1-alpha.9.tgz
    version: 0.2.1-alpha.9
```

(Chart.yaml in package)

```yaml
apiVersion: v2
appVersion: 0.1.27
dependencies:
- name: argo-cd
  repository: https://codefresh-io.github.io/argo-helm
  version: 5.29.1-1-cap-CR-17237
- name: argo-events
  repository: https://codefresh-io.github.io/argo-helm
  version: 2.0.5-1-cf-init
- condition: argo-workflows.enabled
  name: argo-workflows
  repository: https://codefresh-io.github.io/argo-helm
  version: 0.22.9-1-CR-17426
- condition: argo-rollouts.enabled
  name: argo-rollouts
  repository: https://codefresh-io.github.io/argo-helm
  version: 2.22.1-1-cap-sw
- name: sealed-secrets
  repository: https://bitnami-labs.github.io/sealed-secrets/
  version: 2.7.3
- alias: tunnel-client
  name: codefresh-tunnel-client
  repository: https://chartmuseum.codefresh.io/codefresh-tunnel-client
  version: 0.1.12
description: A Helm chart for Codefresh gitops runtime
home: https://github.com/codefresh-io/gitops-runtime-helm
keywords:
- codefresh
- gitops
maintainers:
- name: codefresh
  url: https://codefresh-io.github.io/
name: gitops-runtime
version: 0.2.1-alpha.9
```
