### ISSUE TITLE
Use urlencode on tracker and hub for DSN connections

### ISSUE THREAD

**Issue by rleffd** [artifacthub/hub#4129]
Hello,

There is a small bug if the password used to connect to database has special characters like ":", "@", "$" etc. with the tracker and hub components because of use of DSN string to connect to db. For db-migrator, all is working well as it not using a DSN. I have not tested the scanner yet, but it seems that it is the same behaviour as hub and tracker because it using a DSN string also.

It would be nice to add an urlencode variable for the db password to values and templates. All components are not using a DSN string to connect to DB, so it is necessary to keep existing password variable and add another one with the password urlencoded.

I've just done a test locally:

```yaml
# Database configuration
db:
  host: "{{ .Values.db_instance_address }}"
  port: "{{ .Values.db_instance_port }}"
  database: {{ .Values.db_instance_app_username }}
  user: {{ .Values.db_instance_app_username }}
  password: {{ .Values.db_instance_app_password }}
  passwordEnc: {{ .Values.db_instance_app_pasword_encoded }}
  sslmode: require
```

and in all templates that is using a DSN string, I changed the secrets to:

```yaml
password: {{ .Values.db.passwordEnc }}
```

It works well :)
