### ISSUE TITLE
Define packages metadata spec

### ISSUE THREAD

**Issue by tegioz** [artifacthub/hub#531]
Artifact Hub uses some trackers to index data from multiple sources. The initial goal was to index packages of multiple kinds, available in other hubs like https://hub.helm.sh, https://operatorhub.io and https://securityhub.dev. To achieve this each of the trackers followed the metadata specification of each of those hubs, as well as how the packages are organized in the source repository (more details in the links below).

https://github.com/falcosecurity/cloud-native-security-hub#adding-a-new-falco-rule
https://helm.sh/docs/topics/charts/#the-chartyaml-file
https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md

Later on, we allowed users to add their own repositories. For each package kind (Helm, Falco, OLM, etc), for convenience, we required users to follow the spec and conventions of the hubs previously mentioned. Whilst I think this is fine, I also think we should support our own spec.

One of the reasons is that there are new package kinds we want to support that may not have a metadata spec defined yet, as there isn't a hub available for them. This is the case of the `OPA policies`, that we want to add support for soon. Another reason is that it'd be great to eventually be able to consolidate the tracking logic and not have to support that many different metadata formats (and probably more to come). We could support all of them for some time but encourage users to use ours when possible. If an entity wants to publish their content to https://operatorhub.io and https://artifacthub.io, it may make sense for them to use the metadata spec of the https://operatorhub.io given that we'll support both and they won't have to duplicate efforts. But in some other cases, they may go directly with ours. In the case of package kinds with no dedicated hub, like `OPA policies`, or hubs that are currently not supported like https://securityhub.dev, users may opt for ours too.

Below is a draft of what could be the Artifact Hub package metadata spec. It's mostly a combination of the specs of the other hubs, taking what we need from each of them and adding some extra custom bits. We could start experimenting with this for `OPA policies`. Regarding packages organization in the source repository, I like how the [OLM operators](https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators) are structured in the community operators repo, but I'm happy to go with something else.

```yaml
version: A SemVer 2 version (required)
name: The name of the package (only alphanum, no spaces, dashes allowed) (required)
displayName: The name of the package nicely formatted (required)
createdAt: The date this package was created (RFC3339 layout) (required)
description: A short description of the package (required)
logoURL: A URL for the package logo. Data URIs are supported (optional, but it improves your package visibility)
digest: String that uniquely identifies this package version (optional)
license: SPDX identifier of the package license (https://spdx.org/licenses/) (optional)
homeURL: The URL of the project home page (optional)
appVersion: The version of the app that this contains (optional)
publisherID: The ID of the entity that will publish this package to Artifact Hub (optional)
containerImage: The container image of the package. The format should match ${REGISTRYHOST}/${USERNAME}/${NAME}:${TAG} (optional)
operator: Whether this package is an Operator (optional, boolean)
deprecated: Whether this package is deprecated (optional, boolean)
keywords: # (optional)
  - A list of keywords about this package
  - Using one or more categories names as keywords will improve your package visibility
links: # (optional)
  - name: Title of the link (required for each link)
    url: URL of the link (required for each link)
readme: | # (optional)
  Package documentation in markdown format

  Content added here will be rendered on Artifact Hub
install: | # (optional)
  Install instructions in markdown format

  Content added here will be displayed when the INSTALL button on the package details page is clicked.
maintainers: # (optional)
  - name: The maintainer name (required for each maintainer)
    email: The maintainer email (required for each maintainer)
provider: # (optional)
  name: The name of the individual, company, or service that provides this package (optional)
```

What do you think @dankohn @mattfarina ?

Please let me know if there is something I've left out. Feedback is very welcome :)
