### ISSUE TITLE
Helm: 0.8.0 No verification mail is sent with the Sign-Up

### ISSUE THREAD

**Issue by elnebuloso** [artifacthub/hub#801]
First of all I want to say that artifacthub is quite ingenious.
But I have a problem with the rollout of the helmet version 0.8.0

No verification mail is sent with the Sign-Up

In the cluster is a SMTP relay which can be accessed via production.smtp-relay.svc.cluster.local. If a new user is created during the Sign-UP, the frontend shows that an email is being sent, but no email is sent, also the logs of the SMTP relay do not show a connect. Is the configuration of the e-mail setting wrong?

Helm Configuration YML:

```
hub:
  email:
    from: "no-reply@artifacthub.local"
    smtp:
      host: "production.smtp-relay.svc.cluster.local"
      port: 25
```
