### ISSUE TITLE
Possible Feature request: Support Helm Controller in the Install section

### ISSUE THREAD

**Issue by vijaySamanuri** [artifacthub/hub#903]
I have a possible feature proposal. I am not sure whether it makes sense or not and please help me to get clarified if i understood the scope of the project wrong. Thanks in Advance :)

There are several Helm operators available and [Helm controller](https://github.com/fluxcd/helm-controller) from weave flux looks promising. 

Generation of `HelmRepository`, `HelmChart` & `HelmRelease` CRDs greatly helps for those who wanted to install helm charts and reconcile continuously through `helm controller`.

for suppose to install prometheus helm chart applying below yaml would result in installation & Reconciliation.

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  releaseName: prometheus
  targetNamespace: monitoring
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 12.0.0
  values:
    replicas: 1
```
I believe it would be beneficial to have an option in `install` section to download even `helmrelease` crd yamls in case anyone wants. 

If this feature makes sense, i can pick up this work and contribute if needed.
